export default [
    {
        id: 1,
        name_cn: 'Cara',
        name_en: 'CARA SHEN',
        instrement: 'Guzheng Artist in Residence',
        about:{
            name:'Cara  古筝教师 ',
            standard: '',
            profile:[
                'Cara 5岁学琴至今， 从小接受专业训练，具有坚实的古筝基础以及丰富的专业音乐理论知识，2006年考入四川音乐学院附中，2011年获得优秀毕业生称号， 同年考入四川音乐学院。 先后师从于周天丽讲师，蒋倩副教授，刘媌副教授，著名教育家、演奏家国家一级演员何成育教授、“中国南派古筝传承者”饶宁新教授。Cara老师培养过许多古筝新生代，可进行中英文教学，所教授学生中均考过5-10级以及演奏级别，曾培养学生考进国家级示范高中（石室中学）',
            ],
            experience:[
                '2007-2008年连续获得中华国际音乐艺术大赛四川分赛区古筝专业组一等奖',
                '2008年韩国音协第22届国际音乐艺术大赛-中国西部赛区-古筝专业组一等奖',
                '香港国际青少年艺术节 四川赛区古筝项目少年B组专业组一等奖',
                '2016年 受邀参加澳大利亚昆士兰大学 孔子学院到当地中小学传播中国文化和演出',
                '2017年 受邀为主讲人在澳大利亚中天寺进行中国乐曲讲座。同年参加布里斯班 佛诞节 演出',
                '2018年 受邀参加澳大利亚布里斯班中国节演出。',
                '2020年 加入四川音乐家协会 古筝学会',
                '2021年 受迪拜世博音乐总监Harout Fazlian之邀参加古筝演奏者试镜 获得 《中国古筝艺术流派讲析》证书',
                '2023年 白玉兰国际音乐节 澳新国际赛区华乐竞演大赛 综合专业组 一等奖',
            ],
            overall_cn:[
                '',
            ],
            overall_en:[
                '',
            ],
        },
        avatar: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/cara_avatar.png',
        image: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/cara_image.jpg',
        position: "Founder",
        position_style: {
            fontSize: '16px',
            fontWeight: '500',
        },
    },
    {
        id: 2,
        name_cn: 'SALLY XI',
        name_en: 'SALLY XI',
        instrement: 'Liuqing Artist in Residence',
        about:{
            name:'Sally             柳琴、中阮教师',
            standard: '',
            profile:[
                '2007年本科就读于山东艺术学院柳琴表演专业，2011年以专业第一的成绩考入山东艺术学院，继续攻读硕士研究生-柳琴演奏与教学',
                '2010年首届柳琴北京邀请赛专业中青组 优秀演奏奖',
                '2011年山东省艺术考级“青少年音乐大赛”荣获 评委会大奖',
                '2012年第四届全国“ 文华艺术院校”奖 弹拨乐组—柳琴第二名',
                '2014年7月获得 山东艺术学院“于希宁奖学金 ”并获得山东艺术学院优秀毕业生 荣誉称号',
                '2023年 白玉兰国际音乐节 澳新国际赛区华乐竞演大赛 综合专业组 一等奖',
            ],
            experience:[
                '2011 年 10 月，参加由山东艺术学院、山东省音乐家协会、台湾台北柳琴室内乐团主办的海峡两岸柳琴艺术交流音乐会，并担任独奏',
                '2012 年跟随济南军区前卫文工团参加建军85周年全军大型民族交响音画《黄河》汇演',
                '2012 年 6 月，赴四川音乐学院参加“柳沁梦霓—朱丽姝柳琴独奏音乐会”，担任特邀嘉宾',
                '2013 年 8 月，跟随山东艺术学院女子弹拨乐团赴台湾参加台北柳琴室内乐团 20 周年团庆系列音乐会担任独奏，获得两岸同行的一致好评',
                '2014年抵澳至今，在布里斯班及黄金海岸参与各大演出活动',
            ],
            contribution:[
                '2013 年，论文《浅析柳琴协奏曲<心中的歌>》在山东省文学艺术界权威音乐杂志《音乐大观》10 月刊正式发表',
                '2014年，独立完成硕士毕业学位论文《刘文金音乐艺术撷要梳拾——柳琴协奏曲<酒歌>音乐分析》',
            ],
        },
        avatar: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/sally_avatar.png',
        image: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/sally_image.jpg',
        position: "Co-founder",
        position_style: {
            fontSize: '16px',
            fontWeight: '500',
        },
    },
    {
        id: 3,
        name_cn: 'RAY LIN',
        name_en: 'RAY LIN',
        instrement: 'Composer in Residence',
        about: [
            'Que ensland Music Award winner Ray Lin is a versatile composer, conductor, arranger, and orchestrator for concert hall and screens. His works has been featured in concerts internationally in the US and China; and through a range of prestigious local, state and national venues and platforms in Australia, including QPAC, Brisbane City Hall, 4MBS Classic FM, ABC ME, SBS, Old Museum Concert Hall, Sydney State Theatre, GOMA and more. Ray’s music has been performed by the Queensland Pops Orchestra, Camerata – QLD’s Chamber Orchestra, Symphony Central Coast, Topology, Queensland Conservatorium Symphony and Wind orchestras, members from Ba Ban Chinese Music Society of New York, Orchestral Naturalis (QCGU) and others. ',
            'Ray has received many outstanding awards for his works, including winning the Contemporary Classical Song of the Year prize at the 2020 Queensland Music Awards, and receiving second place in the 2021 National Youth Arranging Competition hosted by Music Arrangers’ Guild Australia. He was awarded the a David Blumberg Award from the American Society of Music Arrangers and Composers in 2022, Honorable Mention Award (Top 5) in Queensland Music Festival’s 2018 “Score-IT(Plus)” film scoring competition and reached the semi-final in the 2020 Walter Hussey Composition Competition (UK). ',
            'Some of Ray’s compositional highlights include being Camerata-Queensland’s Chamber Orchestra’s emerging composer-in-residence for 2023, receiving a commission from the Australian Broadcasting Corporation (ABC, 2022), premiering a chamber work for a East-west cross-cultural ensemble in New York in 2022, co-composed the soundtracks for the 2021 “European Masterpieces” exhibition sound installation project in Queensland Gallery of Modern Arts (exhibition in collaboration with Metropolitan Museum of New York); premiering an orchestral tribute “Waltz No.007” at the Film-Harmonic concert (at part of Brisbane Festival 2021); premiered “The Royal Fanfare” performed by the Queensland Pops Orchestra at the QPAC Concert Hall, premiered two pieces in the 2020 “One World, One Family” 24-hour virtual concert hosted and broadcasted by Chinese CCTV, etc.',
            'Ray is also an active arranger and orchestrator for commercial concerts and media projects, he has arranged/orchestrated for the BrisAsia Festival “Rare Voices” concert (2023), Brisbane Festival “Film Harmonic” concert (2022), “Know It Alls” TV show (ABC ME), 2019 IAUTV Spring Festival Gala 2018 Teressa Teng tribute concert supporting Lord Mayor’s Trust, 2017 Brisbane Chinese Festival Gala show (City Hall) and many more.',        
            'Ray holds a Bachelor of Music (in composition) with distinction from Queensland Conservatorium Griffith University, and he was a recipient of the Sir Samuel Griffith Scholarship and Alan Lane Award for Composition. Ray has also been selected to participate in the Juilliard School of Music 2023 Summer Extension Programs for Composition and Conducting. Ray is currently undertaking the Masters of Arts Screen: Music course at the Australian Film, Television and Radio School.',        
            'As a multi-instrumentalist, Ray had performed in the US, Australia and China; in a variety of live concerts, musical orchestras, commercial events as a guitarist, bassist, and keyboardist. Ray earned Grade 8 certificate for both guitar and bass early in his musical journey, and some notable performances include the 2019 Brisbane Chinese Cultural Festival (Brisbane City Hall), 2019 QYO “Concert at Twilight”, 2017 Pacific Basin Music Festival (Hawaii, USA), 2017 & 2019 Essentially Ellington Jazz Music Festival, and numerous musical productions in Brisbane.',
        ],
        about:{
            name:'RAY LIN             COMPOSER, ARRANGER,',
            standard: '',
            profile:[
                'Queensland Music Award winner Ray Lin is a versatile composer, conductor, arranger, and orchestrator for concert hall and screens. His works has been featured in concerts internationally in the US and China; and through a range of prestigious local, state and national venues and platforms in Australia, including QPAC, Brisbane City Hall, 4MBS Classic FM, ABC ME, SBS, Old Museum Concert Hall, Sydney State Theatre, GOMA and more. Ray’s music has been performed by the Queensland Pops Orchestra, Camerata – QLD’s Chamber Orchestra, Symphony Central Coast, Topology, Queensland Conservatorium Symphony and Wind orchestras, members from Ba Ban Chinese Music Society of New York, Orchestral Naturalis (QCGU) and others. ',
                'Ray has received many outstanding awards for his works, including winning the Contemporary Classical Song of the Year prize at the 2020 Queensland Music Awards, and receiving second place in the 2021 National Youth Arranging Competition hosted by Music Arrangers’ Guild Australia. He was awarded the a David Blumberg Award from the American Society of Music Arrangers and Composers in 2022, Honorable Mention Award (Top 5) in Queensland Music Festival’s 2018 “Score-IT(Plus)” film scoring competition and reached the semi-final in the 2020 Walter Hussey Composition Competition (UK). ',
                'Some of Ray’s compositional highlights include being Camerata-Queensland’s Chamber Orchestra’s emerging composer-in-residence for 2023, receiving a commission from the Australian Broadcasting Corporation (ABC, 2022), premiering a chamber work for a East-west cross-cultural ensemble in New York in 2022, co-composed the soundtracks for the 2021 “European Masterpieces” exhibition sound installation project in Queensland Gallery of Modern Arts (exhibition in collaboration with Metropolitan Museum of New York); premiering an orchestral tribute “Waltz No.007” at the Film-Harmonic concert (at part of Brisbane Festival 2021); premiered “The Royal Fanfare” performed by the Queensland Pops Orchestra at the QPAC Concert Hall, premiered two pieces in the 2020 “One World, One Family” 24-hour virtual concert hosted and broadcasted by Chinese CCTV, etc.',
                'Ray is also an active arranger and orchestrator for commercial concerts and media projects, he has arranged/orchestrated for the BrisAsia Festival “Rare Voices” concert (2023), Brisbane Festival “Film Harmonic” concert (2022), “Know It Alls” TV show (ABC ME), 2019 IAUTV Spring Festival Gala 2018 Teressa Teng tribute concert supporting Lord Mayor’s Trust, 2017 Brisbane Chinese Festival Gala show (City Hall) and many more.',        
                'Ray holds a Bachelor of Music (in composition) with distinction from Queensland Conservatorium Griffith University, and he was a recipient of the Sir Samuel Griffith Scholarship and Alan Lane Award for Composition. Ray has also been selected to participate in the Juilliard School of Music 2023 Summer Extension Programs for Composition and Conducting. Ray is currently undertaking the Masters of Arts Screen: Music course at the Australian Film, Television and Radio School.',        
                'As a multi-instrumentalist, Ray had performed in the US, Australia and China; in a variety of live concerts, musical orchestras, commercial events as a guitarist, bassist, and keyboardist. Ray earned Grade 8 certificate for both guitar and bass early in his musical journey, and some notable performances include the 2019 Brisbane Chinese Cultural Festival (Brisbane City Hall), 2019 QYO “Concert at Twilight”, 2017 Pacific Basin Music Festival (Hawaii, USA), 2017 & 2019 Essentially Ellington Jazz Music Festival, and numerous musical productions in Brisbane.',
            ],
        },
        avatar: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/ray-avatar.jpg',
        image: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/ray-image.jpg',
        position: "",
        position_style: {
        },
    },
    {
        id: 4,
        name_cn: '张楚楚',
        name_en: 'CHUCHU ZHANG',
        instrement: 'Pipa Artist in Residence',
        about: [
            '张楚楚             琵琶教师',
            '',
            '',
            '本科毕业于西安音乐学院民乐系琵琶专业',
            '硕士毕业于昆士兰大学音乐学与音乐教育专业',
            '畅想世博系列评选活动——畅想世博大型群艺互动电视展评活动，陕西分赛区青年器乐组金奖',
            '第七届“德艺双馨”中国文艺展示活动，陕西分赛区，二等奖',
            '首届“省城民族弹拨乐”大赛青年组比赛三等奖',
            '太原市第十六届学校艺术教育活动月器乐比赛琵琶组三等奖',
            '大学连续四年被评为“优秀学生”并荣获“学院奖学金”',
            '大学期间，两年获得“国家级奖学金”',
            '2014和2015年硕士期间，在昆士兰大学中国学生学者联合会举办的中秋',
            '晚会中担任总导演职务，并唱开场曲，以及琵琶独奏',
        ],
        about:{
            name:'张楚楚             琵琶教师',
            standard: '',
            profile:[
                '本科毕业于西安音乐学院民乐系琵琶专业',
                '硕士毕业于昆士兰大学音乐学与音乐教育专业',
            ],
            experience:[
                '畅想世博系列评选活动——畅想世博大型群艺互动电视展评活动，陕西分赛区青年器乐组金奖',
                '第七届“德艺双馨”中国文艺展示活动，陕西分赛区，二等奖',
                '首届“省城民族弹拨乐”大赛青年组比赛三等奖',
                '太原市第十六届学校艺术教育活动月器乐比赛琵琶组三等奖',
                '大学连续四年被评为“优秀学生”并荣获“学院奖学金”',
                '大学期间，两年获得“国家级奖学金”',
                '2014和2015年硕士期间，在昆士兰大学中国学生学者联合会举办的中秋',
                '晚会中担任总导演职务，并唱开场曲，以及琵琶独奏',
            ],
        },
        avatar: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/%E5%BC%A0%E6%A5%9A%E6%A5%9A_avatar.png',
        image: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/%E5%BC%A0%E6%A5%9A%E6%A5%9A_image.jpg',
        position: "",
        position_style: {
        },
    },
    {
        id: 5,
        name_cn: 'Anna 陈芳慧',
        name_en: 'ANNA CHEN',
        instrement: 'Erhu Artist in Residence',
        about:{
            name:'Anna 陈芳慧             二胡教师',
            standard: '教学程度：AAAAA级       教学费用：$80/60分钟（一对一）',
            profile:[
                '六岁学琴至今，以优异成绩毕业于中国音乐学院，学习期间师从于刘顺副教授 （硕博导师，中国紫禁城室内乐团音乐总监兼指挥）。 研究生毕业于昆士兰大学，学习期间师从于Prof. Julie Ballantyne。',
            ],
            experience:[
                '演出足迹遍布海内外各大艺术节及国家音乐厅：',
                '匈牙利国家音乐舞蹈艺术节；李斯特音乐学院中国专场音乐会。',
                '国家艺术基金《意象. 净土》大型民族管弦乐原创作品音乐会巡演。',
                '录制CCTV 风华国乐',
                '悉尼歌剧院',
                '布里斯班亚洲BrisAsian2023文化节, 并获得Channel 9 电视台报道。',
            ],
            contribution:[
                '音乐研究领域：探索和研究音乐与心理，文化，社会的结合；柯达伊音乐教学法研究；东欧民族民间音乐；曾参与第35届音乐ISME 国际音乐教育会议。',
                '作为音乐教师，曾担任北京市科技园小学，玉泉小学二胡指导老师。教学经验丰富，培养孩子开放，包容，多元，创新的人文艺术品格。以二胡作为传播媒介，让更多的海外华人和孩子了解中国传统音乐之美。',
            ],
        },
        avatar: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/anna_avatar.png',
        image: 'https://ywmusic-resource.s3.ap-southeast-2.amazonaws.com/teacher/anna_image.jpg',
        position: "",
        position_style: {
        },
    },
    
]